version: '3.8'

services:
  postgresdb:
    build: .
    volumes:
      - guri-raadi-data:/var/lib/postgresql/data
      - ~/allback:/backups
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}

  app:
    image: node:18-alpine
  
    command: sh -c "apk --no-cache add --virtual .builds-deps build-base python3 &&  npm i && npm rebuild argon2 --build-from-source  && npm run start-dev"
    ports:
      - 8080:8080
    working_dir: /GuriRaadi
    volumes: 
      - ./:/GuriRaadi
    
    depends_on:
      - postgresdb
volumes:
  guri-raadi-data: